/** Traditional Chinese copy for the standalone /admin UI (not under next-intl). */

export const adminCopy = {
  brand: "Soft Boring",
  metadataTitle: "管理後台 · Soft Boring Weekly",
  nav: {
    dashboard: "總覽",
    members: "會員",
    payments: "付款",
    reviews: "回顧",
    wall: "軟軟牆",
    logout: "登出",
  },
  login: {
    title: "管理後台登入",
    leadBefore: "此頁不在前台導覽。請使用環境變數",
    leadAfter: "裡的權杖。",
    missingToken:
      "伺服器尚未設定 ADMIN_TOKEN。請寫入 .env.local 或 /etc/softboring.env，然後重新啟動。",
    tokenLabel: "管理權杖",
    error: "權杖不符。請再試一次。",
    submit: "登入",
  },
  dashboard: {
    title: "總覽",
    members: "會員",
    softPlus: "Soft+",
    free: "Free",
    reviews: "回顧",
    wallNotes: "牆上便利貼",
    succeededPayments: "成功付款",
    revenue: "收入",
    signupsTitle: "最近八週註冊",
    signupsLead: "依建立帳號的週次計算。",
    signupsLabel: "最近八週每週新增會員人數長條圖",
    mixTitle: "Soft+ 與 Free",
    mixLead: "目前有效方案的比例。",
    mixLabel: (plus: number, free: number) =>
      `方案比例：Soft+ ${plus} 人，Free ${free} 人`,
    note: "前台導覽不會連到這裡。Stripe Checkout 與發票會透過 webhook 寫入付款紀錄。若尚未設定 Stripe，付款紀錄會是空的。OAuth 與驗證信仍是之後的事。",
  },
  members: {
    title: "會員",
    empty: "還沒有帳號。",
    email: "電子郵件",
    nickname: "小綽號",
    noNickname: "尚未設定",
    plan: "方案",
    status: "狀態",
    created: "建立時間",
    lastActive: "最近活動",
    reviews: "回顧",
    wall: "軟軟牆",
    stripe: "Stripe",
    actions: "方案操作",
    select: "選取",
    noCustomer: "沒有顧客編號",
    noSubscription: "沒有訂閱編號",
    delete: "刪除",
    deleteConfirm: (email: string) => `要刪除 ${email} 以及其回顧嗎？`,
    demoBadge: "Demo",
  },
  member: {
    title: "會員",
    back: "← 會員列表",
    email: "電子郵件",
    nickname: "小綽號",
    plan: "方案",
    subscriptionStatus: "訂閱狀態",
    created: "建立時間",
    lastActive: "最近活動",
    planUpdated: "方案更新時間",
    stripeCustomer: "Stripe 顧客",
    stripeSubscription: "Stripe 訂閱",
    stripePrice: "Stripe 價格",
    reviews: "回顧",
    wallNotes: "牆上便利貼",
    planHint: "手動改方案是給補償或客服用的，不會向 Stripe 收費，也不會建立訂閱。",
    listHint:
      "在列表上就能給 Soft+：按「設為 Soft+」，確認後立刻生效。不必先點進會員頁。",
    grantPlus: "給予 Soft+",
    setRowPlus: "設為 Soft+",
    setRowFree: "改回免費",
    bulkPlus: "將已選設為 Soft+",
    bulkConfirm: (count: number) =>
      `要將 ${count} 位會員設為 Soft+ 嗎？這是補償／客服用，不會向 Stripe 收費。`,
    select: "選取",
    setFree: "改為 Free",
    setFreeClear: "改為 Free 並清除 Stripe 編號",
    grantConfirm: (email: string) =>
      `要給予 ${email} Soft+ 嗎？這是補償／客服用，不會向 Stripe 收費。`,
    freeConfirm: (email: string) => `要將 ${email} 改為 Free 嗎？會保留 Stripe 編號。`,
    freeClearConfirm: (email: string) =>
      `要將 ${email} 改為 Free，並清除 Stripe 顧客／訂閱編號嗎？`,
    updateError: "無法更新這位會員。",
    deleteMember: "刪除會員",
    reviewsHeading: "回顧",
    reviewsEmpty: "還沒有回顧。",
    when: "時間",
    locale: "語系",
    summary: "摘要",
    quietWeek: "安靜的一週",
    wallHeading: "牆上便利貼",
    wallEmpty: "還沒有牆上便利貼。",
    praise: "稱讚",
    hidden: "已隱藏",
    yes: "是",
    no: "否",
    paymentsHeading: "付款",
    paymentsEmpty: "這位會員還沒有付款紀錄。",
    kind: "類型",
    status: "狀態",
    amount: "金額",
    description: "說明",
  },
  payments: {
    title: "付款",
    kind: "類型",
    status: "狀態",
    email: "電子郵件",
    emailPlaceholder: "包含…",
    all: "全部",
    filter: "篩選",
    clear: "清除",
    emptyFiltered: "沒有符合這些條件的付款。",
    empty:
      "還沒有付款紀錄。成功的 Stripe 結帳、發票與貼紙事件會寫到這裡。若尚未設定 Stripe，這份列表會保持空白。",
    when: "時間",
    member: "會員",
    memberFallback: "會員",
    amount: "金額",
    description: "說明",
    kinds: {
      subscription: "訂閱",
      sticker: "貼紙",
      other: "其他",
    } as Record<string, string>,
    statuses: {
      succeeded: "成功",
      pending: "待處理",
      failed: "失敗",
      refunded: "已退款",
    } as Record<string, string>,
  },
  reviews: {
    title: "回顧",
    empty: "還沒有回顧。",
    when: "時間",
    owner: "擁有者",
    locale: "語系",
    summary: "摘要",
    quietWeek: "安靜的一週",
    guest: (id: string) => `訪客 ${id.slice(0, 8)}`,
    detailTitle: "回顧",
    back: "← 回顧列表",
    noLocale: "沒有語系",
    ownerLabel: "擁有者",
    feeling: (value: number) => `感覺 ${value}／5`,
    energy: "能量",
    drain: "消耗",
    lessOf: "少做一點",
    priorities: "優先事項",
    summaryField: "摘要",
    deleteReview: "刪除回顧",
    deleteConfirm: "要刪除這篇回顧嗎？",
  },
  wall: {
    title: "軟軟牆",
    empty: "還沒有牆上便利貼。",
    when: "時間",
    owner: "擁有者",
    summary: "摘要",
    praise: "稱讚",
    hidden: "已隱藏",
    quietWeek: "安靜的一週",
    yes: "是",
    no: "否",
    hide: "隱藏",
    unhide: "取消隱藏",
    updateError: "無法更新這張便利貼。",
  },
  common: {
    dash: "—",
    deleteError: "無法刪除。",
    planSoftPlus: "Soft+",
    planFree: "Free",
  },
} as const;

export function paymentKindLabel(kind: string) {
  return adminCopy.payments.kinds[kind] ?? kind;
}

export function paymentStatusLabel(status: string) {
  return adminCopy.payments.statuses[status] ?? status;
}
